# Site metadata
name: 'Your name' # Your name
bio: 'Hello, World.' # Your bio
cover: '' # Cover in Homepage
social:
  - name: github
    url: ''
  - name: twitter
    url: ''

# Site SEO
SEOTitle: 'title for SEO' # Only used to generate HTML <title> for SEO.
keyword: 'keyword' # The keywords of your website
description: 'description' # The description of your website
thumbnail: '' # The first thing people will see when someone shares your website. Make sure it stands out.

# Site settings
favicon: ''

# Post metadata
authors:
  - name: ''
    avatar: ''

copyright:
  name: 署名-非商业性使用-禁止演绎 4.0 国际 (CC BY-NC-ND 4.0)
  link: https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh

powerBy: true

analytics:
  google: ''
