# Site metadata
name: 'Your name' # Your name
bio: 'Hello, World.' # Your bio
cover: '' # Cover in Homepage
social:
  - name: github
    url: ''
  - name: twitter
    url: ''

# Site SEO
SEOTitle: 'title for SEO' # Only used to generate HTML <title> for SEO.
keyword: 'keyword' # The keywords of your website
description: 'description' # The description of your website
thumbnail: '' # The first thing people will see when someone shares your website. Make sure it stands out.

# Site settings
favicon: ''

analytics:
  google: ''

deploy:
  github:
    username: ''
    repo: ''
    branch: gh-pages
